routes/web.php
<?php

use App\Http\Controllers\BackeHomeController;
use App\Http\Controllers\Back\CategoryController;
use App\Http\Controllers\Back\ProductController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\WebSiteController;
use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

// $super_admin = false;
// $roles = Role::get();
// $count_roles = count($roles);

// if ($count_roles == 0) {
//     Route::get('/', function () {
//         return view('sedder');
//     });
// } else {
//     Route::get('/', function () {
//         return view('welcome');
//     });
// }

// Route::post('/create-sedder', function () {
//     $role = Role::create([
//         'name' => 'super_admin',
//     ]);

//     $permissions = [
//         'role',
//         'product',
//         'category',
//         'sub_category',
//     ];

//     foreach ($permissions as $key => $permission) {
//         $permission = Permission::create(['name' => $permission]);
//         $permission->assignRole($role);
//     }
// })->name('sedder');

Route::prefix('back')->name('back.')->group(function () {
    Route::get('/', BackeHomeController::class)->middleware('auth')->name('index');

    Route::controller(CategoryController::class)->middleware('auth')->group(function () {
        Route::get('/allcategory', 'index')->name('allcategory');
        Route::get('/addcategory', 'Addcategory')->name('addcategory');
        Route::post('/store-category', 'storecategory')->name('storecategory');
        Route::get('/edit-category/{id}', 'editcategory')->name('editcategory');
        Route::post('/update-category/{id}', 'updatecategory')->name('updatecategory');
        Route::get('/delete-category/{id}', 'deletecategory')->name('deletecategory');

    });


    Route::controller(ProductController::class)->middleware('auth')->group(function () {
        Route::get('/all-product', 'index')->name('allproduct');
        Route::get('/add-product', 'Addproduct')->name('addproduct');
        Route::post('/store-product', 'storeproduct')->name('storeproduct');
        Route::get('/edit-product/{id}', 'editproduct')->name('editproduct');
        Route::post('/update-product/{id}', 'updateproduct')->name('updateproduct');
        Route::get('/delete-product/{id}', 'deleteproduct')->name('deleteproduct');
    });

    Route::controller(RolesController::class)->group(function () {
        Route::get('all-roles', 'index')->name('roles.index');
        Route::get('roles/new/create', 'create')->name('roles.create');
        Route::post('roles/new/store', 'store')->name('roles.store');
    });
});
require __DIR__ . '/auth.php';

Route::controller(WebSiteController::class)->group(function(){
    Route::get('/', 'home')->name('home');
    Route::get('/category/{id}','category')->name('category');
    Route::get('/product-detials/{id}','singleproduct')->name('singleproduct');
});
// Route::get('/', function () {
//           return view('welcome');
//          });

app/Http/Controllers/Back/CategoryController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class CategoryController extends Controller
{
    // Constructor with middleware to check user permissions
    public function __construct(){
        $this->middleware('can:category');
    }

    // Display all categories
    public function index(){
        // get all categories with their associated images, ordered by the latest
        $categories = Category::with(['images'])->latest()->get();
        return view('back.allcategory', compact('categories'));
    }

    public function Addcategory(){
        // get all categories from the model
        $category_info = Category::all();
        return view('back.addcategory', compact('category_info'));
    }

    // Store a new category in the database
    public function storecategory(Request $request){
        try {
            // Validate the incoming request
            $this->validate($request, [
                'image' => 'required',
                'category_name' => 'required',
                'parent_id' => 'nullable|exists:categories,id',
            ]);

            // Create a new Category instance
            $category = new Category();
            $category->category_name = $request->category_name;
            $category->parent_id = $request->parent_id;
            $category->save();
            // Save the image associated with the category

            if ($request->has('image')) {
                $image = save_image('image', 'App\Models\Category', $category->id, $request);
            }

            // Redirect with success message
            return redirect()->route('back.allcategory', compact('category'))->with('success', 'Category created successfully');
        } catch (\Throwable $th) {
            // Redirect with error message
            return redirect()->route('back.allcategory')->with(['error' => 'such as error!']);
        }
    }

    // Display the form to edit a category
    public function editcategory($id){
        // Find the category by ID
        $category_info = Category::findOrFail($id);
        return view('back.editcategory', compact('category_info'));
    }

    // Update an existing category in the database
    public function updatecategory(Request $request, $id) {
        // Validate the incoming request data
        $data = $this->validate($request, [
            'category_name' => 'required|string|max:255',
            'image' => 'sometimes|image|mimes:jpeg,png,jpg,gif|max:2048',
        ]);
        // Find the category by ID
        $category_info = Category::findOrFail($id);
        // Update category information
        $category_info->category_name = $request->category_name;
        // Check if a new image is provided
        if ($request->has('image')) {
            // Delete the old image and its record
            if (File::exists($category_info->images->image ?? '')) {
                File::delete($category_info->images->image);
                Image::where(['id' => $category_info->images->id])->delete();
            }
            // Save the new image
            save_image('image', 'App\Models\Category', $category_info->id, $request);
        }
        // Save the updated category
        $category_info->save();
        // Redirect with success or error message
        if ($category_info) {
            return redirect()->route('back.allcategory')->with(['success' => 'Category Update Successfully!']);
        } else {
            return redirect()->route('back.allcategory')->with(['error' => 'such as error!']);
        }
    }

    // Delete a category from the database
    public function deletecategory($id){
        // Delete the category by ID
        $category_info = Category::where(['id' => $id])->delete();
        // Redirect with success message
        if ($category_info) {
            return redirect()->route('back.allcategory')->with(['success' => 'Delete Successfully']);
        }
    }
}

app/Http/Controllers/Back/ProductController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Image;
use App\Models\Product;
use Illuminate\Support\Facades\File;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    // Constructor with middleware to check user permissions
    public function __construct(){
        $this->middleware('can:product');
    }

    // Display all products
    public function index(){
    // Get all products ordered by the latest
        $allproduct = Product::latest()->get();
        return view('back.allproduct', compact('allproduct'));
    }

    // Display the form to add a new product
    public function Addproduct(){
    // Get all products and categories from the model
        $product_info = Product::all();
        $categories = Category::get();
        return view('back.addproduct',compact('product_info','categories'));
    }

    // Store a new product in the database
    public function storeproduct(Request $request){
        try {
    // Validate the incoming request
            $this->validate($request, [
                'image' => 'required',
                'product_name' => 'required',
                'product_des' => 'required',
                'price' => 'required',
                'category_id' => 'required',
            ]);
    // Create a new Product instance
            $product_info = new Product();
            $product_info->product_name = $request->product_name;
            $product_info->product_des = $request->product_des;
            $product_info->price = $request->price;
            $product_info->category_id = $request->category_id;
            $product_info->save();
    // Save the image associated with the product
            if ($request->has('image')) {
                $image = save_image('image', 'App\Models\Product', $product_info->id, $request);
            }
    // Redirect with success message
            return redirect()->route('back.allproduct', compact('product'))->with(['success', 'Product created successfully']);
        } catch (\Throwable $th) {
    // Redirect with error message
            return redirect()->route('back.allproduct')->with(['error' => 'such as error!']);}
    }

    // Display the form to edit a product
    public function editproduct($id){
    // Find the product by ID with its associated images and categories
        $product_info = Product::with('images')->where(['id' => $id])->first();
        $categories = Category::get();
        return view('back.editproduct', compact('product_info','categories'));
    }

    // Update an existing product in the database
    public function updateproduct(Request $request , $id){
    // Validate the incoming request data
        $data = $this->validate($request, [
            'product_name' => 'required',
            'product_des' => 'required',
            'price' => 'required',
            'category_id' => 'required',
        ]);

        // Find the product by ID
        $product_info = Product::findOrFail($id);
        // Update product information
        $product_info->category_id = $request->category_id ?? $product_info->category_id;
        $product_info->product_name = $request->product_name ?? $product_info->product_name;
        $product_info->product_des = $request->product_des ?? $product_info->product_des;
        $product_info->price = $request->price ?? $product_info->price;
                // Delete the old image and its record
        if (File::exists($product_info->images->image ?? '')) {
            File::delete($product_info->images->image);
            Image::where(['id' => $product_info->images->id])->delete();
        }
                // Save the new image
        save_image('image', 'App\Models\Product', $product_info->id, $request);
                // Save the updated product
        $product_info->save();
                // Redirect with success or error message
        if ($product_info) {
            return redirect()->route('back.allproduct')->with(['success'=>'Product Update Successfully!']);
        } else {
            return redirect()->route('back.allproduct')->with(['error' => 'such as error!']);
        }
    }

    // Delete a product from the database
    public function deleteproduct($id){
                // Delete the product by I
        $product_info = Product::where(['id' => $id])->delete();
        // Redirect with success message
        if ($product_info) {
            return redirect()->route('back.allproduct')->with(['success' => ' Product Delete Successfully']);
        }
    }
}

resources/views/back/addcategory.blade.php
@extends('back.master')
@section('title', 'Add Category')
{{-- @section('home_active', 'active') --}}

@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Page/</span> Add Category </h4>
    <div class="col-xxl">
        <div class="card mb-4">
          <div class="card-header d-flex align-items-center justify-content-between">
            <h5 class="mb-0">Add New Category</h5>
            <small class="text-muted float-end">Input information</small>
          </div>
          <div class="card-body">
            <form action="{{ route('back.storecategory') }}" method="POST" enctype="multipart/form-data">
                @csrf

              <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="basic-default-name">Category Name</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="category_name" name="category_name"
                  />
                </div>
              </div>

              <div class="row mb-3">
                <label for="parent_id">Parent Category</label>
                <select name="parent_id" id="parent_id" class="form-control">
                    <option value="" selected>Select Parent Category</option>
                    @foreach($category_info as $category)
                        <option value="{{ $category->id }}">{{ $category->category_name }}</option>
                    @endforeach
                </select>
            </div>

              <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="basic-default-name">Uploade Category Image </label>
                <div class="col-sm-10">
                    <input class="form-control" type="file" id="image" name="image" />
                </div>
              </div>

              <div class="row justify-content-end">
                <div class="col-sm-10">
                  <button type="submit" class="btn btn-primary">Add Category</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
 </div>

@endsection

resources/views/back/addproduct.blade.php
@extends('back.master')
@section('title', 'Add Product')
{{-- @section('home_active', 'active') --}}

@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Page/</span> Add Product  </h4>
    <div class="col-xxl">
        <div class="card mb-4">
          <div class="card-header d-flex align-items-center justify-content-between">
            <h5 class="mb-0">Add New Product</h5>
            <small class="text-muted float-end">Input information</small>
          </div>
          <div class="card-body">
            @if ($errors->any())
            <div class="alert alert-danger">
           <ul>
           @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
           @endforeach
           </ul>
           </div>
           @endif
            <form action="{{ route('back.storeproduct') }}" method="POST" enctype="multipart/form-data">
                @csrf

              <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="basic-default-name">Product Name </label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="product_name" name="product_name"
                  placeholder="Electronics" />
                </div>
              </div>

              <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="basic-default-name">Product Price </label>
                <div class="col-sm-10">
                  <input type="number" class="form-control" id="price" name="price"
                  placeholder="12" />
                </div>
              </div>

              <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="basic-default-name">Product  Descriptions </label>
                <div class="col-sm-10">
                    <textarea class="form-control" name="product_des" id="product_des" cols="30" rows="10"></textarea>
                </div>
              </div>

              <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="category_id">Select Category</label>
                <div class="col-sm-10">
                    <select class="form-select" id="category_id" name="category_id" aria-label="Default select example">
                        <option selected>Open this select menu</option>
                        @foreach ( $categories as $category )
                        <option value="{{ $category->id }}">{{ $category->category_name }}</option>
                        @endforeach
                      </select>
                </div>
              </div>

              <div class="row mb-3">
                <label class="col-sm-2 col-form-label" for="basic-default-name">Uploade Product Image </label>
                <div class="col-sm-10">
                    <input class="form-control" type="file" id="image" name="image" />
                </div>
              </div>

              <div class="row justify-content-end">
                <div class="col-sm-10">
                  <button type="submit" class="btn btn-primary">Add Product</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
 </div>
@endsection

resources/views/back/allcategory.blade.php
@extends('back.master')
@section('title', 'All Category')
@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Page/</span> All Category </h4>
        <div class="card">
            <h5 class="card-header">Available Categoty Information</h5>
            @if (session()->has('message'))
                <div class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
            @endif
            <div class="table-responsive text-nowrap">
                <table class="table">
                    <thead class="table-light">
                        <tr>
                            <th>Id</th>
                            <th>Category Name</th>
                            <th>Image Category</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody class="table-border-bottom-0">
                        @foreach ($categories as $category)
                            <tr>
                                <td>{{ $category->id }}</td>
                                <td>{{ $category->category_name }}</td>
                                <td><img src="{{ asset($category->images->image ?? '') }}" style="height:100px;"></td>
                                <td>
                                    <a href="{{ route('back.editcategory', $category->id) }}"
                                        class="btn btn-primary">Edit</a>
                                    <a href="{{ route('back.deletecategory', $category->id) }}"
                                        class="btn btn-warning">Delete</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection

resources/views/back/allproduct.blade.php
@extends('back.master')
@section('title', 'All Product')
{{-- @section('home_active', 'active') --}}

@section('content')
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Page/</span> All  Product </h4>
    <div class="card">
        <h5 class="card-header">Available  All Product  Information</h5>
        @if (session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
        @endif
        <div class="table-responsive text-nowrap">
          <table class="table">
            <thead class="table-light">
              <tr>
                <th>Id</th>
                <th>Product Name</th>
                <th>Img</th>
                <th>Price</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0">
                @foreach ( $allproduct as $product )
              <tr>
                <td>{{ $product->id }}</td>
                <td>{{ $product->product_name }}</td>
                {{-- <td>{{ $product->product_name }}</td> --}}
                <td>
                    <img src="{{ asset($product->images->image ?? '') }}" style="height:100px;">
                </td>
                <td>{{ $product->price }}</td>
                <td>
                  <a href="{{ route('back.editproduct',$product->id) }}" class="btn btn-primary">Edit</a>
                  <a href="{{ route('back.deleteproduct', $product->id) }}" class="btn btn-warning">Delete</a>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
</div>
@endsection

resources/views/back/editcategory.blade.php
@extends('back.master')
@section('title', 'Edit Category')

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Page/</span> Edit Category </h4>
        <div class="col-xxl">
            <div class="card mb-4">
                <div class="card-header d-flex align-items-center justify-content-between">
                    <h5 class="mb-0">Edit Category</h5>
                    <small class="text-muted float-end">Input information</small>
                </div>
                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('back.updatecategory', $category_info->id) }}" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label" for="basic-default-name">Category Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="category_name" name="category_name"
                                    value="{{ $category_info->category_name }}" />
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label" for="basic-default-name">Uploade Category Image </label>
                            <div class="col-3">
                                <img class="avatar mb-4" src="{{ asset($category_info->images->image ?? '') }}"
                                    alt="" style="width: 50% ; height:50%">

                                <input class="form-control" type="file" id="image" name="image" accept="image/*"
                                    value="{{ $category_info->image }}" />
                            </div>
                        </div>

                        <div class="row justify-content-end">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Update Category</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/back/editproduct.blade.php
@extends('back.master')
@section('title', 'Edit Product')
{{-- @section('home_active', 'active') --}}

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Page/</span> Edit Product </h4>
        <div class="col-xxl">
            <div class="card mb-4">
                <div class="card-header d-flex align-items-center justify-content-between">
                    <h5 class="mb-0">Edit Product</h5>
                    <small class="text-muted float-end">Input information</small>
                </div>
                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('back.updateproduct', $product_info->id) }}" method="POST"
                        enctype="multipart/form-data">
                        @csrf

                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label" for="basic-default-name">Product Name </label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="product_name" name="product_name"
                                    value="{{ $product_info->product_name }}" />
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label" for="basic-default-name">Product Price </label>
                            <div class="col-sm-10">
                                <input type="number" class="form-control" id="price" name="price"
                                    value="{{ $product_info->price }}" />
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label" for="basic-default-name">Product Descriptions </label>
                            <div class="col-sm-10">
                                <input class="form-control" name="product_des" id="product_des" cols="30"
                                    rows="10" value="{{ $product_info->product_des }}" />
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label" for="basic-default-name">Select Category</label>
                            <div class="col-sm-10">
                                <select class="form-select" id="category_id" name="category_id"
                                    aria-label="Default select example">
                                    <option selected>Open this select menu</option>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->category_name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label" for="basic-default-name">Uploade Product Image </label>
                            <div class="col-2">
                                <img class="avatar mb-4" src="{{ asset($product_info->images->image ?? '') }}"
                                    alt="" style="width: 100%">

                                <input class="form-control" type="file" id="image" name="image" accept="image/*"
                                    value="{{ $product_info->image }}" />
                            </div>
                        </div>

                        <div class="row justify-content-end">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">update Product</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/back/master.blade.php
<!DOCTYPE html>

<html lang="en" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default"
    data-assets-path="{{ asset('assets-back') }}/" data-template="vertical-menu-template-free">

@include('back.partials.head')

@livewireStyles

<body>
        
    @livewireScripts

    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">

            @include('back.partials.sidebar')

            <!-- Layout container -->
            <div class="layout-page">
                @include('back.partials.header')

                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->

                    <div class="container-xxl flex-grow-1 container-p-y">
                        @yield('content')
                    </div>
                    <!-- / Content -->

                    @include('back.partials.footer')


                    <div class="content-backdrop fade"></div>
                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->
        <div class="layout-overlay layout-menu-toggle"></div>
    </div>
    <!-- / Layout wrapper -->


    @include('back.partials.scripts')
    @if (session()->has('success'))
    <script>
        toastr.success("{{ session()->get('success') }}", 'Success');
    </script>
    @elseif (session()->has('error'))
    <script>
        toastr.error("{{ session()->get('error') }}", 'Erorr!');
    </script>
    @endif
</body>

</html>