routes/web.php
<?php

use App\Http\Controllers\BackeHomeController;
use App\Http\Controllers\Back\CategoryController;
use App\Http\Controllers\Back\ProductController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\WebSiteController;
use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

// $super_admin = false;
// $roles = Role::get();
// $count_roles = count($roles);

// if ($count_roles == 0) {
//     Route::get('/', function () {
//         return view('sedder');
//     });
// } else {
//     Route::get('/', function () {
//         return view('welcome');
//     });
// }

// Route::post('/create-sedder', function () {
//     $role = Role::create([
//         'name' => 'super_admin',
//     ]);

//     $permissions = [
//         'role',
//         'product',
//         'category',
//         'sub_category',
//     ];

//     foreach ($permissions as $key => $permission) {
//         $permission = Permission::create(['name' => $permission]);
//         $permission->assignRole($role);
//     }
// })->name('sedder');

Route::prefix('back')->name('back.')->group(function () {
    Route::get('/', BackeHomeController::class)->middleware('auth')->name('index');

    Route::controller(CategoryController::class)->middleware('auth')->group(function () {
        Route::get('/allcategory', 'index')->name('allcategory');
        Route::get('/addcategory', 'Addcategory')->name('addcategory');
        Route::post('/store-category', 'storecategory')->name('storecategory');
        Route::get('/edit-category/{id}', 'editcategory')->name('editcategory');
        Route::post('/update-category/{id}', 'updatecategory')->name('updatecategory');
        Route::get('/delete-category/{id}', 'deletecategory')->name('deletecategory');

    });


    Route::controller(ProductController::class)->middleware('auth')->group(function () {
        Route::get('/all-product', 'index')->name('allproduct');
        Route::get('/add-product', 'Addproduct')->name('addproduct');
        Route::post('/store-product', 'storeproduct')->name('storeproduct');
        Route::get('/edit-product/{id}', 'editproduct')->name('editproduct');
        Route::post('/update-product/{id}', 'updateproduct')->name('updateproduct');
        Route::get('/delete-product/{id}', 'deleteproduct')->name('deleteproduct');
    });

    Route::controller(RolesController::class)->group(function () {
        Route::get('all-roles', 'index')->name('roles.index');
        Route::get('roles/new/create', 'create')->name('roles.create');
        Route::post('roles/new/store', 'store')->name('roles.store');
    });
});
require __DIR__ . '/auth.php';

Route::controller(WebSiteController::class)->group(function(){
    Route::get('/', 'home')->name('home');
    Route::get('/category/{id}','category')->name('category');
    Route::get('/product-detials/{id}','singleproduct')->name('singleproduct');
});
// Route::get('/', function () {
//           return view('welcome');
//          });

app/Http/Controllers/Back/CategoryController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class CategoryController extends Controller
{
    // Constructor with middleware to check user permissions
    public function __construct(){
        $this->middleware('can:category');
    }

    // Display all categories
    public function index(){
        // get all categories with their associated images, ordered by the latest
        $categories = Category::with(['images'])->latest()->get();
        return view('back.allcategory', compact('categories'));
    }

    public function Addcategory(){
        // get all categories from the model
        $category_info = Category::all();
        return view('back.addcategory', compact('category_info'));
    }

    // Store a new category in the database
    public function storecategory(Request $request){
        try {
            // Validate the incoming request
            $this->validate($request, [
                'image' => 'required',
                'category_name' => 'required',
                'parent_id' => 'nullable|exists:categories,id',
            ]);

            // Create a new Category instance
            $category = new Category();
            $category->category_name = $request->category_name;
            $category->parent_id = $request->parent_id;
            $category->save();
            // Save the image associated with the category

            if ($request->has('image')) {
                $image = save_image('image', 'App\Models\Category', $category->id, $request);
            }

            // Redirect with success message
            return redirect()->route('back.allcategory', compact('category'))->with('success', 'Category created successfully');
        } catch (\Throwable $th) {
            // Redirect with error message
            return redirect()->route('back.allcategory')->with(['error' => 'such as error!']);
        }
    }

    // Display the form to edit a category
    public function editcategory($id){
        // Find the category by ID
        $category_info = Category::findOrFail($id);
        return view('back.editcategory', compact('category_info'));
    }

    // Update an existing category in the database
    public function updatecategory(Request $request, $id) {
        // Validate the incoming request data
        $data = $this->validate($request, [
            'category_name' => 'required|string|max:255',
            'image' => 'sometimes|image|mimes:jpeg,png,jpg,gif|max:2048',
        ]);
        // Find the category by ID
        $category_info = Category::findOrFail($id);
        // Update category information
        $category_info->category_name = $request->category_name;
        // Check if a new image is provided
        if ($request->has('image')) {
            // Delete the old image and its record
            if (File::exists($category_info->images->image ?? '')) {
                File::delete($category_info->images->image);
                Image::where(['id' => $category_info->images->id])->delete();
            }
            // Save the new image
            save_image('image', 'App\Models\Category', $category_info->id, $request);
        }
        // Save the updated category
        $category_info->save();
        // Redirect with success or error message
        if ($category_info) {
            return redirect()->route('back.allcategory')->with(['success' => 'Category Update Successfully!']);
        } else {
            return redirect()->route('back.allcategory')->with(['error' => 'such as error!']);
        }
    }

    // Delete a category from the database
    public function deletecategory($id){
        // Delete the category by ID
        $category_info = Category::where(['id' => $id])->delete();
        // Redirect with success message
        if ($category_info) {
            return redirect()->route('back.allcategory')->with(['success' => 'Delete Successfully']);
        }
    }
}

app/Http/Controllers/Back/ProductController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Image;
use App\Models\Product;
use Illuminate\Support\Facades\File;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    // Constructor with middleware to check user permissions
    public function __construct(){
        $this->middleware('can:product');
    }

    // Display all products
    public function index(){
    // Get all products ordered by the latest
        $allproduct = Product::latest()->get();
        return view('back.allproduct', compact('allproduct'));
    }

    // Display the form to add a new product
    public function Addproduct(){
    // Get all products and categories from the model
        $product_info = Product::all();
        $categories = Category::get();
        return view('back.addproduct',compact('product_info','categories'));
    }

    // Store a new product in the database
    public function storeproduct(Request $request){
        try {
    // Validate the incoming request
            $this->validate($request, [
                'image' => 'required',
                'product_name' => 'required',
                'product_des' => 'required',
                'price' => 'required',
                'category_id' => 'required',
            ]);
    // Create a new Product instance
            $product_info = new Product();
            $product_info->product_name = $request->product_name;
            $product_info->product_des = $request->product_des;
            $product_info->price = $request->price;
            $product_info->category_id = $request->category_id;
            $product_info->save();
    // Save the image associated with the product
            if ($request->has('image')) {
                $image = save_image('image', 'App\Models\Product', $product_info->id, $request);
            }
    // Redirect with success message
            return redirect()->route('back.allproduct', compact('product'))->with(['success', 'Product created successfully']);
        } catch (\Throwable $th) {
    // Redirect with error message
            return redirect()->route('back.allproduct')->with(['error' => 'such as error!']);}
    }

    // Display the form to edit a product
    public function editproduct($id){
    // Find the product by ID with its associated images and categories
        $product_info = Product::with('images')->where(['id' => $id])->first();
        $categories = Category::get();
        return view('back.editproduct', compact('product_info','categories'));
    }

    // Update an existing product in the database
    public function updateproduct(Request $request , $id){
    // Validate the incoming request data
        $data = $this->validate($request, [
            'product_name' => 'required',
            'product_des' => 'required',
            'price' => 'required',
            'category_id' => 'required',
        ]);

        // Find the product by ID
        $product_info = Product::findOrFail($id);
        // Update product information
        $product_info->category_id = $request->category_id ?? $product_info->category_id;
        $product_info->product_name = $request->product_name ?? $product_info->product_name;
        $product_info->product_des = $request->product_des ?? $product_info->product_des;
        $product_info->price = $request->price ?? $product_info->price;
                // Delete the old image and its record
        if (File::exists($product_info->images->image ?? '')) {
            File::delete($product_info->images->image);
            Image::where(['id' => $product_info->images->id])->delete();
        }
                // Save the new image
        save_image('image', 'App\Models\Product', $product_info->id, $request);
                // Save the updated product
        $product_info->save();
                // Redirect with success or error message
        if ($product_info) {
            return redirect()->route('back.allproduct')->with(['success'=>'Product Update Successfully!']);
        } else {
            return redirect()->route('back.allproduct')->with(['error' => 'such as error!']);
        }
    }

    // Delete a product from the database
    public function deleteproduct($id){
                // Delete the product by I
        $product_info = Product::where(['id' => $id])->delete();
        // Redirect with success message
        if ($product_info) {
            return redirect()->route('back.allproduct')->with(['success' => ' Product Delete Successfully']);
        }
    }
}

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolesController extends Controller
{

    public function __construct()
    {
        $this->middleware('can:role');
    }

    public function index()
    {
        $roles = Role::get();
        $permissions = Permission::get();
        return view('back.roles.index', compact('roles', 'permissions'));
    }

    public function create()
    {
        $permissions = Permission::get();
        return view('back.roles.create', compact('permissions'));
    }

    public function store(Request $request)
    {
        try {
            $data = $this->validate($request, [
                'role' => 'required',
                'permission' => 'required',
            ]);
            $checked = false;
            $role = new Role();
            $role->name = $data['role'];
            $role->guard_name = 'web';
            $role->save();

            foreach ($request->permission as $key => $permission) {
                $role->givePermissionTo($permission);
                $checked = true;
            }

            if ($checked) {
                return back()->with(['success' => 'Added Role With Permission Successfully']);
            } else {
                return back()->with(['error' => 'Such as Error!']);
            }
        } catch (\Throwable $th) {
            return back()->with(['error' => $th->getMessage()]);
        }
    }
}

resources/views/back/roles/create.blade.php
@extends('back.master')
@section('title', 'Add Role')
{{-- @section('home_active', 'active') --}}

@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Page/</span> Add Role </h4>
        <div class="col-xxl">
            <div class="card mb-4">
                <div class="card-header d-flex align-items-center justify-content-between">
                    <h5 class="mb-0">Add New Role</h5>
                    <small class="text-muted float-end">Input information</small>
                </div>
                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('back.roles.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label" for="basic-default-name">Role Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="role" name="role" />
                            </div>
                        </div>

                        <h5 class="mb-0">Permissions</h5>

                            <div class="col-sm-10">
                                @foreach ($permissions as $permission)
                                    <div class="form-check form-switch">
                                        <label class="form-check-label"
                                        for="permission{{ $permission->id }}">{{ $permission->name }}</label>

                                        <input class="form-check-input" id="flexSwitchCheckDefault"
                                         type="checkbox" name="permission[]" id="permission{{ $permission->id }}"
                                            value="{{ $permission->name }}">
                                    </div>
                                @endforeach
                            </div>

                        <div class="row justify-content-end">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Add Role</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/back/roles/index.blade.php
@extends('back.master')
@section('title', 'All Roles')

@section('content')

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Page/</span> All Roles </h4>
    <div class="card">
        <h5 class="card-header">Available Roles Information</h5>
        <div class="table-responsive text-nowrap">
            <table class="table">
                <thead class="table-light">
                    <tr>
                        <th>ID</th>
                        <th>Role Name</th>
                      
                    </tr>
                </thead>
                <tbody class="table-border-bottom-0">
                    @foreach ( $roles as $role )

                    <tr>
                        <td>{{ $role->id }}</td>
                        <td>{{ $role->name }}</td>

                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endsection